### PR TITLE
Missions setup

### PR DESCRIPTION
**Pull request by RoyJumah**
> In this pull request I setup files for the missionReducer and ConfigureStore and I also styled the navigation to show the active navigation link

### CODE REVIEW

**Review by yuvenalmash — APPROVED** [review]
Good work @roy 👍🏾 
This branch is ready to be merged 🎉

**Comment by rvandermeij-godaddy** [comment]
Thanks, not sure what I did, though :)

**Comment by roy** [comment]
Thanks! Not sure what I did though ;)

**Comment by yuvenalmash** [comment]
Sorry, I tagged the wrong Roy 😆

**Pull request merged**
